[package]
name = "hydrogen_net_proc_macro"
version = "0.1.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
const-fnv1a-hash = "1.1.0"
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = "2.0.71"
typetag = "0.2.18"
